# NumPy

## Basics of NumPy

In [ ]:
Creating an Array
Select the correct option to create a 1-d array using the following elements (1.0, 2, 3.5, 0.2, True). 
(Note that ‘True’ must be provided as a Boolean value, not as a string.)


np.array(1.0, 2, 3.5, 0.2, True)

np.array( [1.0, 2, 3.5, 0.2, "True"] )

np.array( [1.0, 2, 3.5, 0.2, True] )   ✓ Correct

In [ ]:
NumPy Array
What is the default data type of each element in the array created in the previous question?


String


Integer


Float    ✓ Correct

In [ ]:
Creating an array
Is it possible to create an array from a tuple?


Yes   ✓ Correct

## Operations Over 1-D Arrays

In [ ]:
Indexing Array
Given an array:

array_1 = [1,2,3,5,4,6,7,8,5,3,2]
What will be the output of the code provided below?

print(array_1[:3])
 


[1, 2, 3, 5]


[1, 2, 3]    ✓ Correct

In [ ]:
Indexing Array
Given an array:

array_1 = [1,2,3,5,4,6,7,8,5,3,2]
What will be the output of the code provided below?

print(array_1[2:-3])
 


[3 5 4 6 7 8]
 

✓ Correct

In [ ]:
Indexing Array
Given an array:

array_1 = [1,2,3,5,4,6,7,8,5,3,2]
What will be the output of the code provided below?
(Hint: The syntax is [starting value : end value : step value])

print(array_1[ : : -2])
 


[2, 5, 6, 8, 3]
 


[1, 3, 4, 7, 5, 2]
 


[2, 5, 7, 4, 3, 1]   ✓ Correct

In [ ]:
Indexing Array
How would you extract all the elements with an odd index in a given array?
(Hint: Odd index refers to the position of the element, not the actual value)


array[1:1]

array[: : 2]

array[1: : 2]
✓ Correct


In [ ]:
Extracting Elements from Array
Description
From a given array, extract all the elements which are greater than 'm' and less than 'n'. Note: 'm' and 'n' are integer values provided as input.



Input format:

A list of integers on line one

Integer 'm' on line two

Integer 'n' on line three



Output format:

1-D array containing integers greater than 'm' and smaller than 'n'.

In [ ]:
import ast 
input_list=ast.literal_eval(input())
m=int(input())
n=int(input())

import numpy as np
array_1 = np.array(input_list)
final_array = array_1[(array_1<n) & (array_1>m)]

print(final_array)



## Practice Exercise I

#### How many different products are sold by the company in total?

-  99
-  100
-  101
-  102


In [13]:
number.size

102

#### How many items were sold in total?

-  460
-  490
-  500
-  520


In [25]:
quantity =  number.sum() 
quantity

490

#### What is the average price of the products sold by the ecommerce company?

-  139
-  151
-  142
-  128

In [22]:
price.mean() 

139.01960784313727

#### What is the price of the costliest item sold?

-  225
-  310
-  280
-  285

In [23]:
price.max() 

285

#### What is the total revenue of the company? [Revenue = Price\*Quantity]

-  67100
-  53900
-  45300
-  71200

In [27]:
revenue = np.sum(price*number) 
revenue

67100

#### Demand for the 20th product in the list is more than the 50th product. [True/False]
-  True
-  False
-  Can't be calculated

In [28]:
number[19]>number[49] 

True

#### How many products fall under the category of expensive goods? 
An expensive good is that good whose price is more than the average price of the products sold by the company.

-  48
-  50
-  52
-  54

In [29]:
price[price > price.mean()].size 

52

## Multidimensional Arrays

In [ ]:
Border Rows and Columns
Description
Extract all the border rows and columns from a 2-D array.

Format:
Input: A 2-D Python list
Output: Four NumPy arrays - First column of the input array, first row of the input array, last column of the input array, last row of the input array respectively.


In [ ]:
import ast,sys
input_str = sys.stdin.read()
input_list = ast.literal_eval(input_str)

import numpy as np


array_2d =np.array(input_list)



col_1 = array_2d[:, 0]
row_1 = array_2d[0, :]
col_last = array_2d[:, -1]
row_last = array_2d[-1, :]

print(col_1)
print(row_1)
print(col_last)
print(row_last)


## Creating NumPy Arrays

In [ ]:
Array 'arange' Function
Description
Create an array of first 10 multiples of 5 using the 'arange' function.

In [ ]:

import numpy as np
array_multipleof5 =  np.arange(5,51,5)

print(array_multipleof5)

In [ ]:
Create border array
Description
Given a single integer n, create an (n x n) 2D array with 1 on the border and 0 on the inside.

Note: Make sure the array is of type int.

Example:
Input 1:
4
Output 1:
[[1 1 1 1]
[1 0 0 1]
[1 0 0 1]
[1 1 1 1]]

In [ ]:
n = int(input())

import numpy as np

border_array = np.ones((n, n), dtype = int)

border_array[1:-1, 1:-1] = 0

print(border_array)

## Mathematical Operations on NumPy

In [ ]:
Index of the 100th Element
Consider an (11,12) shape array. What is the index (x,y) of the 100th element? Note: For counting the elements, go row-wise. For example, in the array:

[[1, 5, 9],
 [3, 0, 2]]
the 5th element would be '0'.


(8, 3)   ✓ Correct

In [ ]:
Reshaping an Array
Suppose you have an array 'p':

[[1, 5],
 [3, 7],
 [4, 9]]
What will be the output of the following code?

np.reshape(p, -1)
 


1-d array   ✓ Correct

In [ ]:
Reshaping an Array
Consider the array provided below: 

[[1, 2, 3, 4, 5]
 [6, 7, 8, 9, 10]
 [11, 12, 13, 14, 15]
 [16, 17, 18, 19, 20]]
Now, you are expected to generate the following array out of it:

[[1, 3]
 [5, 7]
 [9, 11]
 [13, 15]
 [17, 19]]
Which code will give you the correct output?
(Hint: Also check if one or more options are correct.)


print(array_1.reshape(5, 4)[array_1%2 != 0])

print(array_1[array_1%2 != 0])

print(array_1[array_1%2 == 0].reshape(5, 2))

print(array_1[array_1%2 != 0].reshape(5, 2))  ✓ Correct

In [ ]:
Reshaping an array
Suppose you have an array 'p'

[[1, 5],
 [3, 7],
 [4, 9]]
What will be the output of the following code?

np.reshape(p, (1, -1))
 


1-D Array


2-D Array   ✓ Correct

In [ ]:
Stacking arrays
Description
Merge the three arrays provided to you to form a one 4x4 array.

[Hint: Check the function np.transpose() in the 'Manipulating Arrays' notebook provided.]

In [ ]:
import ast,sys
input_str = sys.stdin.read()
input_list = ast.literal_eval(input_str)
list_1 = input_list[0]
list_2 = input_list[1]
list_3 = input_list[2]

import numpy as np

final_array = np.hstack([np.vstack([np.array(list_1),np.array(list_2)]), np.transpose(np.array(list_3))])
print(final_array)


## Practice Exercise II

#### Q-1: What are the dimensions of the array created using the list 'score'?

-  1
-  2
-  3
-  4


In [10]:
score.ndim 

2

#### Q-2: How many players scored zero runs in their inning?

-  20
-  22
-  24
-  26


In [9]:
len(score[score[:,0]==0])

26

#### Q-3: What is the maximum number of wickets taken by a player?

-  4
-  6
-  3
-  5

In [11]:
np.max(score[:, 1])

4

#### Q-4: Find the ID of the player who scored the maximum runs in the innings


-  193
-  219
-  548
-  1021


In [12]:
player[score[:, 0] == np.max(score[:, 0])]

array([548])

#### Q-5: You are asked to check for all-rounders within the given set of players. How many all-rounders are present in the provided list?
An all-rounder is someone who is good in both, batting and bowling.
Check if the individual has taken 2 or more wickets and scored more than 35 runs in their innings

-  5
-  6
-  7
-  8

In [13]:
len(score[(score[:, 0]>35) & (score[:, 1]>=2)])

6

# pandas

## Basics of Pandas


In [ ]:
Loading a csv in Pandas
Description
Create a dataframe from the file ‘marks.csv’ and print the contents of the dataframe. Open the file from the link above and inspect the required elements in the file (header, separator, etc.). If the top row is a regular entry, do not load it as the column header.

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/A08MajL8qN4rq72EpVJbAP1Rw/marks_1.csv', sep='|', header=None)

x = pd.DataFrame(df)
print(x)

## Pandas - Rows and Columns


In [ ]:
Setting the Index
Which of the following functions is used to change the name of an existing index in a dataframe?


df.set_index

df.index_name

df.index.name    ✓ Correct

In [ ]:
Loading a csv with index
Description
Using the file ‘marks.csv’, create a dataframe as shown below.

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/A08MajL8qN4rq72EpVJbAP1Rw/marks_1.csv', sep = '|', index_col=0,header=None)
df.index.name = 'S.No.'
# df.columns = ['Name','Subject']
df.columns = ['Name','Subject','Maximum Marks','Marks Obtained','Percentage']

print(df)

## Describing Data


In [ ]:
Hierarchical Indexing
Description
You are provided with the dataset of a company which has offices across three cities - Mumbai, Bangalore and New Delhi. The dataset contains the rating (out of 5) of all the employees from different departments (Finance, HR, Marketing and Sales). 



Create a hierarchical index based on two columns: Office and Department



Print the first 5 rows as the output. Refer to the image below for your reference.



In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/NMgEjwkAEGGQZBoNYGr9Ld7w0/rating.csv', index_col = [2,1])
df.sort_index(inplace=True)
ds = df.head()
print(ds)

In [ ]:
Describing Data
Which of the following commands would you use to check the count of all the entries in each column in the dataframe as well as the count of the non-null entries in each column in the dataframe at the same time?


describe()


info()   ✓ Correct

In [ ]:
DataFrames
Description
Given a dataframe 'df' use the following commands and analyse the result.
describe() 
columns
shape

In [ ]:
import numpy as np
import pandas as pd
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF.csv')
print(df.describe())
print(df.columns)
print(df.shape)

## Indexing and Slicing

In [ ]:
Selecting Columns of a Dataframe
Description
Print out the columns 'month', 'day', 'temp', 'area' from the dataframe 'df'.

In [ ]:
import pandas as pd
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df_2 = df[["month","day","temp","area"]]
print(df_2.head(20))

In [ ]:
Indexing Dataframes
Description
Print only the even numbers of rows of the dataframe 'df'.

Note: Don't include the row indexed zero.

In [ ]:
import pandas as pd
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df_2 = df.iloc[::2,:]
x = df_2.drop(0)
print(x.head(20))

In [ ]:
Indexing and Slicing
Take a look at the dataframe (‘df’) provided below.


df.loc[[2], ["S.No.", "Name", "Subject", "Percentage"]]

df.loc[[3], ["Name", "Subject", "Percentage"]]   ✓ Correct

df.iloc[[2], [0, 1, 4]]    ✓ Correct

In [ ]:
iloc vs loc
What is the difference between the use of iloc and loc?

In [ ]:
The functionalities of iloc and loc are different; iloc fetches the rows/columns at a particular position (and hence takes an integer as input), whereas loc fetches rows/columns with particular labels.

In [ ]:
Applying Conditions on Dataframes
Description
Print all the columns and the rows where 'area' is greater than 0, 'wind' is greater than 1 and the 'temp' is greater than 15.

In [ ]:
import pandas as pd
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df_2 = df[(df["area"]>0)&(df["wind"]>1)&(df["temp"]>15)]
print(df_2.head(20))


## Operations on Dataframes

In [ ]:
Description
You are provided with the dataset of a company which has offices across three cities - Mumbai, Bangalore and New Delhi. The dataset contains the rating (out of 5) of all the employees from different departments (Finance, HR, Marketing and Sales). 



The company has come up with a new policy that any individual with a rating equal to or below 3.5 needs to attend a training. Using dataframes, load the dataset and then derive the column ‘Training’ which shows ‘Yes’ for people who require training and ‘No’ for those who do not.



In [ ]:
import numpy as np
import pandas as pd
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
df = pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/NMgEjwkAEGGQZBoNYGr9Ld7w0/rating.csv')
df['Training'] = df.Rating.apply(lambda x: 'Yes' if x <= 3.5 else 'No')
print(df.head())

In [ ]:
Dataframe
 In the dataframe created above, find the department that has the most efficient team (the team with minimum percentage of employees who need training).


Finance


HR    ✓ Correct

## Groupby and Aggregate Functions

In [ ]:
Groupby function
What does the function: dataframe.groupby() return without any aggregate function?


A new dataframe is created


A Pandas object is created   ✓ Correct

In [ ]:
Dataframe grouping
Description
Group the dataframe 'df' by 'month' and 'day' and find the mean value for column 'rain' and 'wind'.

In [ ]:
import pandas as pd
df = pd.read_csv('https://cdn.upgrad.com/uploads/production/b3467ba4-4e13-44e9-8087-4d7e94cc7586/forestfires.csv')
by = df.groupby(['month', 'day'])
df_1 = by['rain','wind'].mean()
print(df_1.head(20))

## Merging DataFrames


In [ ]:
Merging Dataframes
Suppose you are provided with two dataframes:
    
df_1.merge(df_2, how = 'left')

df_1.merge(df_2, how = 'right')

df_1.merge(df_2, how = 'inner')  ✓ Correct

In [ ]:
Dataframes Merge
Description
Perform an inner merge on two data frames df_1 and df_2 on  'unique_id' and print the combined dataframe.

In [ ]:
import pandas as pd
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
df_1 = pd.read_csv('https://query.data.world/s/vv3snq28bp0TJq2ggCdxGOghEQKPZo')
df_2 = pd.read_csv('https://query.data.world/s/9wVKjNT0yiRc3YbVJaiI8a6HGl2d74')
df_3 = df_1.merge(df_2, on = 'unique_id',how = 'inner')
print(df_3.head(20))


In [ ]:
Dataframe Append
Description
Append two datasets df_1 and df_2, and print the combined dataframe.

####    wrong answer  #####
import warnings
warnings.simplefilter("ignore")

import pandas as pd
df_1 = pd.read_csv('https://query.data.world/s/vv3snq28bp0TJq2ggCdxGOghEQKPZo')
df_2 = pd.read_csv('https://query.data.world/s/9wVKjNT0yiRc3YbVJaiI8a6HGl2d74')

df_3 = pd.concat([df_1, df_2])

print(df_3.head())

Operations on multiple dataframes
Description
Given three data frames containing the number of gold, silver, and bronze Olympic medals won by some countries, determine the total number of medals won by each country. 

Note: All three data frames don’t have all the same countries. So, ensure you use the ‘fill_value’ argument (set it to zero), to avoid getting NaN values. Also, ensure you sort the final data frame, according to the total medal count in descending order. Make sure that the results are in integers.

In [ ]:
import numpy as np 
import pandas as pd
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
gold = pd.DataFrame({'Country': ['USA', 'France', 'Russia'],
                         'Medals': [15, 13, 9]}
                    )
silver = pd.DataFrame({'Country': ['USA', 'Germany', 'Russia'],
                        'Medals': [29, 20, 16]}
                    )
bronze = pd.DataFrame({'Country': ['France', 'USA', 'UK'],
                        'Medals': [40, 28, 27]}
                    )

gold.set_index('Country', inplace = True)
silver.set_index('Country', inplace = True) 
bronze.set_index('Country', inplace = True) 

total = gold.add(silver, fill_value = 0).add(bronze, fill_value = 0)
total = total.sort_values(by = 'Medals', ascending = False)
# total_1 = 
print(total.astype(int))

## Pivot Tables

In [ ]:
Dataframe Pivot Table
Description
Group the data 'df' by 'month' and 'day' and find the mean value for column 'rain' and 'wind' using the pivot table command.

In [ ]:
import numpy as np
import pandas as pd
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df_1 = df.pivot_table(index = ['month','day'], aggfunc = 'mean')
df_2 = df_1[['rain','wind']]
print(df_2.head(20))

## Practice Exercise

In [ ]:
Structure of a Dataframe
How many rows and columns are present in the dataframe? 


(3821, 26)


(3879, 28)


(3853, 28)    ✓ Correct

In [ ]:
Columns with Null values
How many columns have null values present in them? Try writing code for this instead of counting them manually.


3


6


9


12   ✓ Correct

In [ ]:
Dropping Columns
What is the count of columns in the new dataframe?


10


13   ✓ Correct

In [ ]:
Deriving a Metric
Which column has the highest percentage of null values?


language    ✓ Correct

In [ ]:
Replacing Null values
What is the count of movies made in the English language after replacing the NaN values with English?


3670


3674   ✓ Correct

In [ ]:
Sorting a dataframe
Which movie is ranked 5th from the top in the list based on the net profit obtained?

Note: net profit = gross - budget


E.T. the Extra-Terrestrial    ✓ Correct

In [ ]:
Analysing dataframes
Suppose movies are divided into 5 buckets based on the IMDb ratings:

[7.5, 8)
[8, 8.5)
[8.5, 9)
[9, 9.5)
[9.5, 10)
Which bucket holds the maximum number of movies from IMDb_Top_250?


[7.5, 8)


[8, 8.5)    ✓ Correct

In [ ]:
Operations on Dataframe
Which actor is highest rated among the three actors according to the user reviews?


Meryl Streep


Leonardo DiCaprio    ✓ Correct

In [ ]:
Operations on Dataframe
Which actor is highest rated among the three actors according to the critics?


Meryl Streep


Leonardo DiCaprio    ✓ Correct

In [1]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>